# Generated by Django 2.1.1 on 2018-09-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='context',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticetype',
            name='name',
            field=models.CharField(choices=[('COMMENT_NOTICE', '评论通知'), ('REPLY_NOTICE', '回复通知')], max_length=50),
        ),
    ]
